@plr = player()


@hero = associative_array(
            'name': '§4A§1t§0o§8m',
            'class': 'Atom',
            'sig': 'qmdu4edsaTeAtbzfyJin4N0H3pX0LDpowED+OoF7NOf17aBsNDmrGDYMidd58L9xwWuc7HuWAwL5TGtLwzLyHKIVdYrOCs274HGkma5SJjq1C66/WBEv6SQKRir/fYleTJibDgXLunhz02FtlZE8D7RrzO1S3ty69L+oeWtrYC7ESjFH8HAUUia7WYMlLARhEXiYarXlSzVmHrPhIpl1ICwNeY/So6MNcOHDF1WCl7LB90sLM7hd60Z+Ppa2jJ5cpz8g6Ektdjpxx0BvOcqoBgreyPoyOrl5+AxXfxDBQgDXz6nKmr0136bo7GMSuVakBudTiukOIzcUIkkM6lyQQFoIh16NGkhwyY9Yn/4v8MlPpJS5iruq7D69Q+dbz/6uagtvHxpmbft2aKbos73fERJGEV6OGuMsxn6qPIATuIapp+8rW6AgR41woKxY8xbnJ3/a3uN04mFHqHPja0KK4325/mNmnOr9l0mqoPwUN9KLlCKlBCMz3XPW1P7/IJ4uDWm9QHSVy2z4fIlYTGVvWFFzVICMQi921yhY7rT8S49L4j29aJYs7+m00d8OnanQ1yUJDvziBMWdi7vgRc14H9NqeUycZ0XuTOgOifdNevp3wnG126a7JQXHeCcxFWgV3FmvsueqlXfquTV4fxSWd0FaX+4X5BL+BhCxmvedKjc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk3MTUzODk0MjMsInByb2ZpbGVJZCI6IjJkYjYyYTM1NjA2NTRjMmM5NjRkZWZjNWUwYWNlMThhIiwicHJvZmlsZU5hbWUiOiJBbmRyZWlNQ1UiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzU5ZjNhZWNlNzUxNWQ1YjVhNzk4ODM1ODkzMWI2OGIyNmJhMjVlOTVlZTdhOWE0NWVmYzMzNzUyYTFmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "WTF I'm small!",
            'powers': array(
                "/buff",
                "/thru",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-2",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." plasmablast",
                "/disguise silverfish"                
            )
        )
