@plr = player()


@hero = associative_array(
            'name': '§4A§8t§1o§fm',
            'class': 'Atom',
            'sig': 'pMNM3q7hqAQWnU50TrXqAkUXNshNdB3vWwX3JWpdl4AsPjGsDQEFbwZRD6zDerwDmU0cdxrEy4qLxAh5sjjGNvBrIOo9SmdnXR5phbg6piFjxiH6bAjv7sTr8/VGaYgyVLijFgmWVLI8lEdNXown/CjRPchqEOt05IqQ0ntsMGyvkdeQpMSzQQ7pmbE3nhDQT1gqp6Y4F5RXGfgLBKo7p9YnZZZC0yygYzE2N1HaaEpIMdq0pkKAqULr33ThfgDRlNqinegJ3FU+FNoSbPjri3RFXjOivSXFppOpgplvcbwOkxK9k3pw0ZaOCyzn3YnHeeppgMRbakg4iRZw0aHUPLxaRmyHs/TAKZytsAgrWhAnxK4/9OTw2vM4CRr9+5/VFMZMdY9OJ5YjzcdM5G6qD6vp/1xabaUj4QKyKxWRmI37N5tlJ/QKgeWuRQut7N8ZtHS7PNslu6MTgt1gGlb6nZ8C3ln5vG0q1e7BBYRy2KqBQ465q+CQh0VYhVuFaaHFbmPYBfQnQLr6vzNGtlWlxctXvHrpZyNb1qvARA0+Cj+v/+oCq5e77hEK796j/vYm1aieJxzvzQSuRpV/Mj/fop2XlSpAOodhwqRtcLHE11OlYtl5iaPs+X9vgHCRDp2MzZj8br3DT/0+ZNv28UIf7QPHZ4lxBExGRzKPVUk72=',
            'val': 'yJ0aW1lc3RhbXAiOjE0ODgzMjkyOTcyNjYsInByb2ZpbGVJZCI6IjJkYjYyYTM1NjA2NTRjMmM5NjRkZWZjNWUwYWNlMThhIiwicHJvZmlsZU5hbWUiOiJBbmRyZWlNQ1UiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzU5ZjNhZWNlNzUxNWQ1YjVhNzk4ODM1ODkzMWI2OGIyNmJhMjVlOTVlZTdhOWE0NWVmYzMzNzUyYTFmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Wtf I'm small!",
            'powers': array(
                "/buff",
                "/thru",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-2",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." plasmabeam",
                "/disguise silverfish"                
            )
        )
